services:
  postgres:
    image: postgres:15
    container_name: myvehiclehub-db
    restart: always
    environment:
      POSTGRES_DB: myvehiclehub
      POSTGRES_USER: nst
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: